# Generated by Django 5.1 on 2024-08-15 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={"verbose_name": "объявление", "verbose_name_plural": "объявления"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "отзыв", "verbose_name_plural": "отзывы"},
        ),
        migrations.AlterField(
            model_name="ad",
            name="created_at",
            field=models.DateField(
                verbose_name=models.DateTimeField(
                    blank=True,
                    default=django.utils.timezone.now,
                    null=True,
                    verbose_name="дата и время создания",
                )
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateField(
                verbose_name=models.DateTimeField(
                    blank=True,
                    default=django.utils.timezone.now,
                    null=True,
                    verbose_name="дата и время создания",
                )
            ),
        ),
    ]
