# Generated by Django 5.1 on 2024-08-15 20:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_ad_options_alter_comment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="author",
            field=models.ForeignKey(
                blank=True,
                default="Anonymous",
                help_text="Автор объявления",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="дата и время создания",
            ),
        ),
    ]
