# Generated by Django 5.1 on 2024-08-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_alter_ad_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="title",
            field=models.CharField(
                help_text="Укажите название товара",
                max_length=150,
                verbose_name="название товара",
            ),
        ),
    ]
